site_name: 'production-01'
site_description: 'Documentation for Confluent Cloud Cluster production-01'

nav:
  - Home: index.md
  - Cluster Details: cluster-details.md
  - Operations: operations.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences 